## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import gkey

# Configure gmaps API key
gmaps.configure(api_key=gkey)

In [5]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,71.46,94,75,6.91,mist
1,1,Cape Town,ZA,-33.9258,18.4232,67.08,81,0,3.44,clear sky
2,2,Souillac,MU,-20.5167,57.5167,75.58,88,75,4.61,broken clouds
3,3,Albany,US,42.6001,-73.9662,35.10,70,48,11.12,scattered clouds
4,4,Bredasdorp,ZA,-34.5322,20.0403,63.72,82,36,6.91,scattered clouds

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

In [14]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
clean_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,71.46,94,75,6.91,mist
1,1,Cape Town,ZA,-33.9258,18.4232,67.08,81,0,3.44,clear sky
2,2,Souillac,MU,-20.5167,57.5167,75.58,88,75,4.61,broken clouds
4,4,Bredasdorp,ZA,-34.5322,20.0403,63.72,82,36,6.91,scattered clouds
7,7,Chuy,UY,-33.6971,-53.4616,68.36,64,11,7.83,few clouds
13,13,Ponta Do Sol,PT,32.6667,-17.1000,66.83,48,40,10.40,scattered clouds
15,15,Butaritari,KI,3.0707,172.7902,82.00,77,71,13.85,broken clouds
16,16,Gorontalo,ID,0.5412,123.0595,74.25,93,100,3.18,overcast clouds
18,18,Tuatapere,NZ,-46.1333,167.6833,60.82,65,93,4.18,light rain
19,19,Port Alfred,ZA,-33.5906,26.8910,70.97,88,6,9.22,clear sky

In [15]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                359
City                   359
Country                354
Lat                    359
Lng                    359
Max Temp               359
Humidity               359
Cloudiness             359
Wind Speed             359
Current Description    359
dtype: int64

In [16]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Arraial Do Cabo,BR,-22.9661,-42.0278,71.46,94,75,6.91,mist
1,1,Cape Town,ZA,-33.9258,18.4232,67.08,81,0,3.44,clear sky
2,2,Souillac,MU,-20.5167,57.5167,75.58,88,75,4.61,broken clouds
4,4,Bredasdorp,ZA,-34.5322,20.0403,63.72,82,36,6.91,scattered clouds
7,7,Chuy,UY,-33.6971,-53.4616,68.36,64,11,7.83,few clouds
...,...,...,...,...,...,...,...,...,...,...
687,687,Manacapuru,BR,-3.2997,-60.6206,75.78,88,96,2.30,moderate rain
690,690,Jardim,BR,-21.4803,-56.1381,73.69,37,0,5.06,clear sky
692,692,Solano,US,38.2333,-121.9511,75.88,40,0,11.50,clear sky
698,698,Kidal,ML,18.4411,1.4078,69.24,9,0,8.77,clear sky
699,699,Sitio Novo Do Tocantins,BR,-5.5183,-47.4611,74.80,92,76,1.25,broken clouds

In [17]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Arraial Do Cabo,BR,71.46,mist,-22.9661,-42.0278,
1,Cape Town,ZA,67.08,clear sky,-33.9258,18.4232,
2,Souillac,MU,75.58,broken clouds,-20.5167,57.5167,
4,Bredasdorp,ZA,63.72,scattered clouds,-34.5322,20.0403,
7,Chuy,UY,68.36,few clouds,-33.6971,-53.4616,
13,Ponta Do Sol,PT,66.83,scattered clouds,32.6667,-17.1000,
15,Butaritari,KI,82.00,broken clouds,3.0707,172.7902,
16,Gorontalo,ID,74.25,overcast clouds,0.5412,123.0595,
18,Tuatapere,NZ,60.82,light rain,-46.1333,167.6833,
19,Port Alfred,ZA,70.97,clear sky,-33.5906,26.8910,

In [19]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [41]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head()
hotel_df.count()
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Arraial Do Cabo,BR,71.46,mist,-22.9661,-42.0278,Pousada Porto Praia
1,Cape Town,ZA,67.08,clear sky,-33.9258,18.4232,Southern Sun Waterfront Cape Town
2,Souillac,MU,75.58,broken clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
4,Bredasdorp,ZA,63.72,scattered clouds,-34.5322,20.0403,Bredasdorp Country Manor
7,Chuy,UY,68.36,few clouds,-33.6971,-53.4616,Nuevo Hotel Plaza
...,...,...,...,...,...,...,...
687,Manacapuru,BR,75.78,moderate rain,-3.2997,-60.6206,Novo Hotel
690,Jardim,BR,73.69,clear sky,-21.4803,-56.1381,Estancia Hotel - Jardim MS
692,Solano,US,75.88,clear sky,38.2333,-121.9511,Westwind Inn
698,Kidal,ML,69.24,clear sky,18.4411,1.4078,
699,Sitio Novo Do Tocantins,BR,74.80,broken clouds,-5.5183,-47.4611,Imperial Hotel

In [27]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [42]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F </dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [46]:
# 11a. Add a marker layer for each city to the map.
marker = clean_hotel_df['Max Temp']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=marker,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))